wandb_version: 1

lmd:
  desc: null
  value: '{''recons'': 1.0, ''latent'': 1e-05, ''kl'': 1e-05, ''contrastive'': 0.1}'
lr:
  desc: null
  value: 0.0001
temp:
  desc: null
  value: 0.1
threshold_selfsim:
  desc: null
  value: 0.8
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715041667.0
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 50
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 49
      - 50
      - 55
      - 103
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
