defaults:
  - defaults
  - _self_

device: cuda

run_dir: /vulcanscratch/mukunds/downloads/TMR/outputs/tmr_humanml3d_guoh3dfeats
protocol: all #  (is all 4), normal (a), threshold (b), nsim (c), guo (d)
threshold: 0.95 # threashold to compute (b)

ckpt: last
batch_size: 256
